# Generated by Django 5.0.4 on 2024-05-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_remove_attendee_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
