# Generated by Django 5.0.4 on 2024-05-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_eventorganizer_phone_number_eventorganizer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(choices=[('VIP', 'VIP Ticket'), ('General', 'General Admission'), ('Student', 'Student Ticket')], default='General', max_length=100),
        ),
    ]
