# Generated by Django 5.0.4 on 2024-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(choices=[('VIP', 'VIP Ticket'), ('General', 'General Admission')], default='General', max_length=100),
        ),
    ]
