# Generated by Django 5.0.4 on 2024-05-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('organizer', 'Event Organizer'), ('attendee', 'Attendee')], max_length=20),
        ),
    ]
