# Generated by Django 5.0.4 on 2024-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_status_customuser_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Event Organizer'), ('admin', 'Administrator')], default='attendee', max_length=20),
        ),
    ]
