# Generated by Django 5.0.4 on 2024-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0002_event_ticket_price_event_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('attended', 'Attended'), ('not_attended', 'Not Attended')], max_length=20),
        ),
    ]
