# Generated by Django 5.0.4 on 2024-05-21 06:02

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_organizer', '0005_alter_attendee_event_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='unknown', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
